{"name": "test_apply_using_invalid_number", "status": "passed", "start": 1663858946271, "stop": 1663858960753, "uuid": "70b2096a-02ab-4070-a6bb-6de1f2e1ddf1", "historyId": "f22ad0612945e78858f0161be9bf457e", "testCaseId": "5299a426c71a075eda0bcf239ceb6244", "fullName": "tests.test_login.TestLoginPage#test_apply_using_invalid_number", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLoginPage"}, {"name": "host", "value": "mm-MS-7B89"}, {"name": "thread", "value": "27026-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}